name: Test de workflow Build

env:
  PROJECT_VERSION: '1.0.0'
  MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository/"

on: 
  push:
    branches: [main] 

jobs:
  build-app:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          # Java distribution. See the list of supported distributions in README file
          distribution: zulu
          java-version: 17
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
           # Artifact name
           name: helloworld-${{ PROJECT_VERSION }}.jar
           # A file, directory or wildcard pattern that describes what to upload
           path: "${{ github.workspace }}/.m2/artifact/"
           # The desired behavior if no files are found using the provided path.
      - name: Cache
        uses: actions/cache@v4.3.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: "${{ github.workspace }}/.m2/repository/"
          # An explicit key for restoring and saving the cache
          key: 'repository_hash'

      - name: "start build"
        run:
          mvn clean package -DskipTests
  test-app:
    name: "Test"
    runs-on: ubuntu-latest
    needs: build-app
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          # Java distribution. See the list of supported distributions in README file
          distribution: zulu
          java-version: 17

      - name: Cache
        uses: actions/cache@v4.3.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: "${{ github.workspace }}/.m2/repository/"
          # An explicit key for restoring and saving the cache
          key: 'repository_hash'

      - name: "start build"
        run:
          mvn test
  
