name: Test de workflow Build

env:
  PROJECT_VERSION: '1.0.0'
  MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository/"
 
on: 
  push:
    branches: [main] 

jobs:
  build-app:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          # Java distribution. See the list of supported distributions in README file
          distribution: zulu
          java-version: 17
      - name: Cache
        uses: actions/cache@v4.3.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: "${{ github.workspace }}/.m2/repository/"
          # An explicit key for restoring and saving the cache
          key: 'repository_hash'

      - name: "start build"
        run:
          mvn clean package -DskipTests
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
           # Artifact name
           path: "target/helloworld-1.0-SNAPSHOT.jar"
           name: helloworld-${{ env.PROJECT_VERSION }}.jar
  test-app:
    name: "Test"
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          # Java distribution. See the list of supported distributions in README file
          distribution: zulu
          java-version: 17

      - name: Cache
        uses: actions/cache@v4.3.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: "${{ github.workspace }}/.m2/repository/"
          # An explicit key for restoring and saving the cache
          key: 'repository_hash'

      - name: "start build"
        run:
          mvn test
          continue-on-error: true
          
